"""Halfway descriptive interpretation, built only after full frozen verification."""
import json
from pathlib import Path
root=Path(__file__).parent
read=lambda n:json.loads((root/n).read_text(encoding='utf-8-sig'))
check=read('integrity.json');assert check['success'] and check['replay_verified']==150 and check['pending_requests']==0
d=read('interim-metrics.json');f=read('repair-forensics.json');focus=read('focused-metrics.json');caps=read('cap-details.json')
c=d['cumulative'];S=c['arms']['strict'];B=c['arms']['bounded'];W=c['arms']['stepwise'];aa=c['arms'];arms=('strict','bounded','stepwise')
rec=B['recovery'];tail=focus['cumulative']['stepwise_tail'];patterns=f['patterns']['cumulative'];rel=f['reliability']['cumulative']
total=lambda k:sum(aa[a]['totals'][k] for a in arms)
lines=['# Halfway decision — INTERIM, 50 matches/control','',
    '**PASS FOR CONTINUATION unchanged. Recommend Batches 6–8 as the next authorization scope, retaining separate frozen gates. Execution stopped after Batch 5; this recommendation does not authorize or execute any later batch.**','',
    'The study is halfway complete: 150 of 300 intended matches. Batch 4 passed the separate mechanical gate before Batch 5 began. All 150 cumulative matches passed exact replay, request accounting reconciled with zero pending requests, and prior roots were preserved. The frozen source/runtime/contract, exact schedule, side/control/model/opponent bindings, seals and no-fallback checks passed. [Final gate](batch-5-gate.md) records the verified counts and hashes.','']
def p(v=''):lines.extend([v,''])
def pct(x):return f'{100*x:.2f}%'
def wln(s):return f"{s['wins']}/{s['losses']}/{s['limits']}"
def table(h,rr):
    lines.append('| '+' | '.join(h)+' |');lines.append('| '+' | '.join('---' for _ in h)+' |')
    for row in rr:lines.append('| '+' | '.join(str(v) for v in row)+' |')
    lines.append('')
table(['Cohort','Strict W/L/no-result; requests','Bounded W/L/no-result; requests','Stepwise W/L/no-result; requests'],[[label,*[wln(d[key]['arms'][a])+'; '+str(d[key]['arms'][a]['totals']['provider_requests']) for a in arms]] for label,key in [('Batch 4','batch_4'),('Batch 5','batch_5'),('Cumulative','cumulative')]])
p('## Seventeen halfway questions')
p('1. **Is the benchmark mechanically healthy?** Yes on the observed evidence: all 150 replays and the required gates passed. All 60 newly authorized matches are sealed, and no later match was started. No prompt, schema, repair, control, opponent, rules, cap or analysis definition was tuned.')
p(f"2. **Is Bounded recovering stale plans reliably?** It replanned {rec['replans']} times and recovered at least one AP on {rec['positive']} ({pct(rec['positive_fraction'])}), recovering {rec['ap_total']} AP in total. Mean/median recovery is {rec['mean_ap_per_replan']:.3f}/{rec['median_ap_per_replan']} AP per replan. This measures mechanical recovery, not match quality.")
extra=B['totals']['provider_requests']-S['totals']['provider_requests'];premium=extra/S['totals']['provider_requests'];turnpremium=B['per_turn']['provider_requests']/S['per_turn']['provider_requests']-1
p(f"3. **What is Bounded's real premium?** Totals are {B['totals']['provider_requests']} versus Strict's {S['totals']['provider_requests']}: a signed difference of {extra:+d} ({pct(premium)}), or {B['per_match']['provider_requests']:.3f} versus {S['per_match']['provider_requests']:.3f} per match. Per attempted Luna turn the rates are {B['per_turn']['provider_requests']:.3f} versus {S['per_turn']['provider_requests']:.3f}, a {pct(turnpremium)} premium. Different trajectories, match lengths and forfeits affect totals. Signed extra requests divided by recovered AP is {extra/rec['ap_total']:.4f}, descriptive and not causal.")
p(f"4. **Has Bounded improved outcomes over Strict?** Observed W/L/no-result is {wln(B)} versus {wln(S)}; win difference is {B['wins']-S['wins']:+d}. Repair-exhaustion forfeits are {rel['bounded']['repairs_exhausted']} versus {rel['strict']['repairs_exhausted']}; Luna Core damage is {B['totals']['core_damage_dealt']} versus {S['totals']['core_damage_dealt']}. Final execution truncations are {B['totals']['execution_truncations']} versus {S['totals']['execution_truncations']}, with truncation-derived AP {B['unused_ap_by_reason']['EXECUTION_TRUNCATION']} versus {S['unused_ap_by_reason']['EXECUTION_TRUNCATION']}. Recovery alone cannot substantiate the bounded outcome/reliability thesis. The frozen paired comparisons remain interim and descriptive.")
p(f"5. **How frequent are second invalidities?** {B['totals']['second_invalidities']}/{rec['replans']} replans ({pct(B['second_invalid_rate'])}). Counts/rates by batch: "+'; '.join(f"{i}: {d[f'batch_{i}']['arms']['bounded']['totals']['second_invalidities']}/{d[f'batch_{i}']['arms']['bounded']['recovery']['replans']}" for i in range(1,6))+'. No acceptability threshold was frozen; these failures remain data under the one-replan limit.')
batchfails=[sum(f['reliability'][str(i)][a]['repairs_exhausted'] for a in arms) for i in range(1,6)]
exhaust=sum(rel[a]['repairs_exhausted'] for a in arms)
p(f'6. **How important are repair forfeits?** There are {exhaust}/150 ({pct(exhaust/150)}) cumulatively, with batch counts {batchfails}. They directly determine recorded losses without natural terminal outcomes. The outcomes without these failures are unknown; no failed game was retried or manually repaired. Counts across five small batches do not by themselves establish a temporal trend or stochastic cause.')
p('7. **Which controls are affected?** '+ '; '.join(f"{a}: {rel[a]['repairs_exhausted']}/50 matches ({pct(rel[a]['repairs_exhausted']/50)}), repair success {rel[a]['repairs_succeeded']}/{rel[a]['repairs_attempted']} ({pct(rel[a]['repair_success_rate'])})" for a in arms)+'. Different decision exposure and game duration preclude equating raw counts with a causal control effect. Full first-response denominators are reported separately.')
geometric=patterns['repair_classifications'].get('STATIC_RANGE_OR_LOS',0)
p(f"8. **Are failures dominated by range/LOS references?** {geometric}/{exhaust} exhausted repairs carry the descriptive static range/LOS tag ({pct(geometric/exhaust)}). Classification counts: `{json.dumps(patterns['repair_classifications'])}`. The official invalid_reference label is broad and can reject a current first action with valid IDs but invalid geometry. AP/schema failures and ambiguous move diagnostics remain separate. The retained initial/repair structured output, validators and receipt evidence support the classification without hidden reasoning or unredacting unknown IDs.")
p(f"9. **Does Stepwise's long tail persist?** Yes descriptively: sorted request counts are `{tail['sorted_requests']}`; mean {tail['mean_including_caps']:.3f}, median {tail['median']}, and uncapped mean {tail['mean_excluding_caps']:.3f}. Uncapped games include early forfeits. The capped-game trace table records repeated unit downs, revivals and healing; these prolonged matches repeatedly incur observation/decision cost. Those trace facts do not prove model intent or a general causal explanation.")
p(f"10. **How often is Stepwise capped?** {tail['capped']}/50 ({pct(tail['cap_rate'])}) at exactly 140 requests. Cap IDs and sides: "+', '.join(x['match_id']+' '+x['luna_side'] for x in caps)+'. Each retains a nonterminal final state and no winner; natural uncapped outcomes are censored. The final Core/unit states and hashes are available in cap-details.json.')
p(f"11. **What share of Stepwise spending comes from caps?** {tail['capped']*140}/{W['totals']['provider_requests']} requests, or {pct(tail['capped_request_share'])}. The cap remains fixed; this concentration is an observed operational result, not a reason to increase it.")
p(f"12. **Is Stepwise's outcome advantage commensurate with cost?** It has {W['wins']} wins versus Bounded's {B['wins']} and Strict's {S['wins']}. Its W/L/no-result is {wln(W)}. Costs are {W['totals']['provider_requests']} requests, {W['totals']['total_tokens']:,} tokens and {W['totals']['provider_latency_seconds']:.2f} provider seconds, versus Bounded's {B['totals']['provider_requests']}, {B['totals']['total_tokens']:,} and {B['totals']['provider_latency_seconds']:.2f}. Per turn, Bounded uses {pct(1-B['per_turn']['provider_requests']/W['per_turn']['provider_requests'])} fewer requests. No value threshold was frozen for deciding whether an outcome gain justifies that cost. Broad Wilson intervals, caps and independent outputs prevent a final control ranking.")
p('13. **Is Heuristic V2 dominant?** Matchup-specific Heuristic W/L/no-result: '+ '; '.join(a+' '+wln(aa[a]['heuristic']) for a in arms)+'. Its model-request cost is zero; measured heuristic computation is reported separately. These are distinct matchups, not a pooled homogeneous skill estimate. The opponent is unchanged.')
ends=sum(aa[a]['end_turn']['count'] for a in arms)
p(f"14. **Do EndTurns behave correctly?** All {ends} explicit stops had zero subsequent requests within the turn. Control totals/immediate stops are "+'; '.join(f"{a}: {aa[a]['end_turn']['count']}/{aa[a]['end_turn']['immediate']}" for a in arms)+'. Legal damaging opportunities at a stop are mechanically audited but do not prove an attack would have been strategically preferable. Intentional, clean completion, truncation, actual provider failure, budget denial and terminal AP remain separate.')
p('15. **Are there interesting Fireball patterns?** '+ '; '.join(f"{a}: {aa[a]['totals']['fireball']} casts, {aa[a]['totals']['friendly_only_fireballs']} friendly-only, {aa[a]['totals']['mixed_fireballs']} mixed, {aa[a]['totals']['empty_fireballs']} empty; friendly damage {aa[a]['fireball']['friendly_damage']}, friendly downs {aa[a]['fireball']['friendly_downs']}" for a in arms)+'. Engine-replayed terminal Fireballs and enemy damage/downs are listed in the main report. Counts reflect different exposure and repeated revive cycles; they are not quality scores or grounds for prompt tuning.')
p('16. **Is there evidence of a contract defect?** No observed hard-stop condition was found. Exact replay, source/runtime checks and evidence reconciliation passed. The recorded failures are interpretable using the frozen current-action and AP validators. This does not prove the design flawless, but there is no evidence supporting a mid-study change. Ordinary model failures and tactical weakness remain benchmark evidence.')
p('17. **Should the second half continue unchanged?** Yes. Mechanical checks remain clean, costs are measurable and bounded, and failure patterns are interpretable. The study must retain its fixed imperfect policy and opponent to answer the intended comparison. The halfway results cannot establish the full bounded thesis from AP recovery alone.')
p('## Statistical and resource limits')
p('Repair reliability is now a major study finding, not just an isolated incident: 31 of 150 matches ended in exhausted-repair forfeits (20.67%), including 17 of 50 Bounded matches (34%). Batch counts 2, 7, 8, 5 and 9 show that the elevated burden persists with variation; they do not establish a monotonic increase. Failures occur in every control, while Bounded has the largest observed match-level burden. Static range/LOS constraints account for 26 of 31 cases (83.87%).')
p('All 1,113 provider receipts from Batches 4–5 record returned responses. The 14 new exhausted repairs therefore have affirmative response evidence, rather than an observed transport outage. Their exact validator reasons are preserved in repair-forensics.md. No failed game was retried.')
p('The hoped-for Bounded win improvement is absent at halfway: Strict and Bounded are both 0/50 wins. Bounded has dealt five Core damage versus Strict\'s zero, a small observed Core-pressure difference that has not produced a win. Bounded reduces final execution truncations but has more repair forfeits. Its selective recovery mechanism works often; these data do not show that it compensates for the tactical and output-reliability limitations against Heuristic V2.')
p('All eight capped Stepwise matches are Luna Red, with final Red Core HP 12 and Blue Core HP 30. Unit configurations differ, so these are not claims of identical full engine states. The new capped games show 41–44 Heuristic revives each and 42–132 Heuristic heals, plus recurring unit downs. Each new capped match reached 47 Luna turns with only 0–2 repairs and 1–2 explicit EndTurns. Thus most capped-game spending comes from repeatedly deciding through a long match, not repair retry volume. The traces do not identify unwillingness to EndTurn as a cause; explicit stop semantics were correct. All eight caps among the 25 Red assignments is a descriptive concentration, not proof of a general side effect.')
table(['Control','Wins / losses / no-result','Win rate','Wilson 95%'],[[a,wln(aa[a]),pct(aa[a]['win_rate']),str(aa[a]['wilson_95'])] for a in arms])
p('Wilson intervals use all completed scheduled matches, including capped nonwins and forfeits. Frozen confirmatory McNemar/Holm and bootstrap inference waits for the full cohort; halfway paired differences, side splits and distributions are descriptive. One canonical opening and service-period/model variation limit generalization. No final winner is declared.')
table(['Resource','Observed 150','Remaining 150 estimate','Full 300 estimate'],[[k,f'{total(k):,.3f}',f'{total(k):,.3f}',f'{2*total(k):,.3f}'] for k in ('provider_requests','total_tokens')]+[['Provider hours',f"{total('provider_latency_seconds')/3600:.4f}",f"{total('provider_latency_seconds')/3600:.4f}",f"{2*total('provider_latency_seconds')/3600:.4f}"]])
walls=[json.loads((Path(f'artifacts/arena-case-study-live-v1-{i:02d}')/'execution-timing.json').read_text(encoding='utf-8-sig'))['wall_seconds_upper_bound'] for i in range(1,6)]
p(f'Observed process wall time totals {sum(walls)/3600:.3f} hours. Repeating the observed batch range gives {5*min(walls)/3600:.3f}–{5*max(walls)/3600:.3f} remaining wall hours, or {(sum(walls)+5*min(walls))/3600:.3f}–{(sum(walls)+5*max(walls))/3600:.3f} full-study hours. This excludes later analysis and is not a guaranteed bound: growing prefix verification and provider conditions can increase it. Provider/backend times overlap; cached input is part of input and reasoning tokens part of output. No frozen pricing exists, so no dollars are estimated.')
p('## Next authorization recommendation')
p(f"Recommend **Batches 6–8 only**, retaining independent 1,700-request ceilings, all per-control/per-match/global guards, and separate frozen integrity gates. At halfway observed rates, 90 further matches imply approximately {total('provider_requests')*.6:,.1f} requests, {total('total_tokens')*.6:,.0f} tokens and {total('provider_latency_seconds')*.6/3600:.3f} provider hours. These are estimates, not increased ceilings. Five batches provide enough operational evidence that individual approval after every batch adds limited value. Reviewing again at 80/control retains a checkpoint before the final two batches. **No Batch 6 or later execution occurred.**")
p('[Batch 4 report](../arena-case-study-live-v1-04/batch-4-report.md) · [Batch 4 gate](../arena-case-study-live-v1-04/batch-4-gate.md) · [Batch 5 report](batch-5-report.md) · [Halfway cumulative report](cumulative-batches-1-5-report.md) · [Focused comparisons](focused-comparisons.md) · [Repair forensics](repair-forensics.md) · [Figures](figures.md)')
(root/'decision.md').write_text('\n'.join(lines),encoding='utf-8')
print(json.dumps(dict(success=True,questions_answered=17,recommendation='Batches 6–8; not executed')))
