"""Interpret verified 80/control evidence; never invokes a model."""
import json
from pathlib import Path
root=Path('artifacts/arena-case-study-live-v1-08')
read=lambda n:json.loads((root/n).read_text(encoding='utf-8-sig'))
check=read('integrity.json');assert check['success'] and check['replay_verified']==240 and check['pending_requests']==0
d=read('interim-metrics.json');f=read('repair-forensics.json');focus=read('focused-metrics.json');caps=read('cap-details.json')
aa=d['cumulative']['arms'];S=aa['strict'];B=aa['bounded'];W=aa['stepwise'];arms=('strict','bounded','stepwise');rel=f['reliability']['cumulative'];rec=B['recovery'];tail=focus['cumulative']['stepwise_tail']
total=lambda k:sum(aa[a]['totals'][k] for a in arms)
pct=lambda n:f'{100*n:.2f}%'
wln=lambda s:f"{s['wins']}/{s['losses']}/{s['limits']}"
lines=['# Decision — INTERIM, 80/100 matches per control','',
    '**PASS FOR CONTINUATION unchanged. Recommend authorizing Batches 9–10 to finish the frozen study. Neither batch was executed.**','',
    'All 240 cumulative matches passed exact replay. Batches 6 and 7 each passed full replay, ledger reconciliation, source/contract and earlier-artifact preservation gates before the next batch started. Batch 8 also passed. The independent 1,700-request batch ceilings remained unchanged; no unused capacity rolled forward. There were no duplicate committed requests, pending requests, heuristic fallback or retries of forfeited matches. Frozen prompts, model/profile, controls, rules, opponent, schedule, metrics and analysis were unchanged.','']
def p(s):lines.extend([s,''])
def table(h,rs):
    lines.append('| '+' | '.join(h)+' |');lines.append('| '+' | '.join('---' for _ in h)+' |')
    for row in rs:lines.append('| '+' | '.join(str(v) for v in row)+' |')
    lines.append('')
table(['Cohort','Strict W/L/no-result; requests','Bounded W/L/no-result; requests','Stepwise W/L/no-result; requests'],[[label,*[wln(d[key]['arms'][a])+'; '+str(d[key]['arms'][a]['totals']['provider_requests']) for a in arms]] for label,key in [('Batch 6','batch_6'),('Batch 7','batch_7'),('Batch 8','batch_8'),('Cumulative','cumulative')]])
p('## Fourteen research questions')
p(f"1. **Does Bounded still reduce execution truncation?** Final truncations are {B['totals']['execution_truncations']} versus Strict's {S['totals']['execution_truncations']}; the count ratio is {B['totals']['execution_truncations']/S['totals']['execution_truncations']:.3f}. At halfway it was 14/119 (0.118). Attempted-turn rates are {B['totals']['execution_truncations']/B['totals']['turns']:.3f} versus {S['totals']['execution_truncations']/S['totals']['turns']:.3f}. Truncation-derived unused AP is {B['unused_ap_by_reason']['EXECUTION_TRUNCATION']} versus {S['unused_ap_by_reason']['EXECUTION_TRUNCATION']}. Counts and rates are both needed because trajectories and match lengths differ.")
p(f"2. **Is AP recovery stable?** Cumulative positive recovery is {rec['positive']}/{rec['replans']} ({pct(rec['positive_fraction'])}), versus 88/99 (88.89%) at halfway. It recovered {rec['ap_total']} AP, mean {rec['mean_ap_per_replan']:.3f} and median {rec['median_ap_per_replan']} per replan. New-batch positive counts: "+'; '.join(f"{b}: {d[f'batch_{b}']['arms']['bounded']['recovery']['positive']}/{d[f'batch_{b}']['arms']['bounded']['recovery']['replans']}" for b in (6,7,8))+f". Second invalidities are {B['totals']['second_invalidities']}/{rec['replans']} ({pct(B['second_invalid_rate'])}). No new acceptance threshold or trend test is introduced.")
p(f"3. **Is there an outcome advantage over Strict?** Bounded versus Strict W/L/no-result: {wln(B)} versus {wln(S)}. Win difference: {B['wins']-S['wins']:+d}. Core damage: {B['totals']['core_damage_dealt']} versus {S['totals']['core_damage_dealt']}; enemy downs: {B['totals']['enemy_units_downed']} versus {S['totals']['enemy_units_downed']}; Finishes: {B['totals']['finish']} versus {S['totals']['finish']}. Repair forfeits are {rel['bounded']['repairs_exhausted']} versus {rel['strict']['repairs_exhausted']}. Mechanical recovery alone does not establish tactical success. Paired differences and terminal causes in the linked tables expose these separate measures rather than combining them into a score.")
extra=B['totals']['provider_requests']-S['totals']['provider_requests'];premium=extra/S['totals']['provider_requests'];turnpremium=B['per_turn']['provider_requests']/S['per_turn']['provider_requests']-1
p(f"4. **Is the request premium stable?** Cumulative per-match premium is {pct(premium)} ({B['per_match']['provider_requests']:.3f} versus {S['per_match']['provider_requests']:.3f} requests/match); per-Luna-turn premium is {pct(turnpremium)} ({B['per_turn']['provider_requests']:.3f} versus {S['per_turn']['provider_requests']:.3f}). Halfway values were 17.58% and 38.14%. New-batch total premiums: "+'; '.join(f"{b}: {pct(d[f'batch_{b}']['arms']['bounded']['totals']['provider_requests']/d[f'batch_{b}']['arms']['strict']['totals']['provider_requests']-1)}" for b in (6,7,8))+f". Signed extra requests / recovered AP is {extra/rec['ap_total']:.4f}, descriptive and not causal. Match length, early forfeits and independent responses influence aggregate costs.")
p('5. **Does Bounded have a higher repair-forfeit burden?** '+ '; '.join(f"{a}: {rel[a]['repairs_exhausted']}/80 ({pct(rel[a]['repairs_exhausted']/80)}), repair success {rel[a]['repairs_succeeded']}/{rel[a]['repairs_attempted']} ({pct(rel[a]['repair_success_rate'])})" for a in arms)+'. All controls are exposed; control-specific decision denominators and per-batch counts are reported in repair-forensics.md. This observational comparison does not identify a stochastic mechanism or establish a causal control effect. Full-turn planning controls and Stepwise must be compared using their different request/turn exposure as well as match-level forfeits.')
full_forfeits=sum(rel[a]['repairs_exhausted'] for a in ('strict','bounded'))
full_first=sum(rel[a]['first_responses'] for a in ('strict','bounded'));full_invalid=sum(rel[a]['first_response_invalid_decisions'] for a in ('strict','bounded'))
p(f"The two full-turn arms jointly have {full_forfeits}/160 repair-forfeit matches ({pct(full_forfeits/160)}), compared with Stepwise {rel['stepwise']['repairs_exhausted']}/80 ({pct(rel['stepwise']['repairs_exhausted']/80)}). First-response invalidity is {full_invalid}/{full_first} ({pct(full_invalid/full_first)}) for those full-turn decision requests, including Bounded replacement plans, versus {rel['stepwise']['first_response_invalid_decisions']}/{rel['stepwise']['first_responses']} ({pct(rel['stepwise']['first_response_invalid_decisions']/rel['stepwise']['first_responses'])}) for Stepwise. This descriptive grouping shows the association and exposure; it does not establish why the policies failed.")
exhaust=sum(rel[a]['repairs_exhausted'] for a in arms);geometry=f['patterns']['cumulative']['repair_classifications'].get('STATIC_RANGE_OR_LOS',0)
p(f"6. **Are exhausted repairs concentrated around range/LOS?** {geometry}/{exhaust} ({pct(geometry/exhaust)}) carry the descriptive static range/LOS tag. All categories: `{json.dumps(f['patterns']['cumulative']['repair_classifications'])}`. Counts by batch are "+str([sum(f['reliability'][str(b)][a]['repairs_exhausted'] for a in arms) for b in range(1,9)])+f". These forfeits directly determine {exhaust}/240 ({pct(exhaust/240)}) losses; outcomes without the failures are unknown. The broad official invalid_reference category can reject geometry with valid IDs. Extra-analysis.md separates explicit range, LOS and ambiguous Fireball range/board diagnostics without rewriting official classifications.")
winners=[a for a in arms if aa[a]['wins']]
p('7. **Is Stepwise the only control with wins?** Controls with observed wins: '+(', '.join(winners) if winners else 'none')+'. Counts: '+', '.join(f"{a} {aa[a]['wins']}/80" for a in arms)+'. This remains an interim sample from one canonical opening, not a final control ranking.')
p(f"8. **Is Stepwise's cost tail still large?** Mean requests/match {tail['mean_including_caps']:.3f}, median {tail['median']}, uncapped mean {tail['mean_excluding_caps']:.3f}; capped games consume {pct(tail['capped_request_share'])} of its requests. Uncapped games include early forfeits. Sorted counts and capped states are reported. p75/p90/p95 are not published by the frozen analyzer and are not added as new inferential outputs.")
p(f"9. **How often is Stepwise capped?** {tail['capped']}/80 ({pct(tail['cap_rate'])}), each at 140 requests, consuming {140*tail['capped']} requests. All capped games retain no winner and a nonterminal final state. Natural uncapped outcomes and length are unknown. Each cap's rounds, Luna turns, AP/actions, repairs, EndTurns, Core/unit state and final hash are retained.")
p(f"10. **Does Stepwise's outcome advantage justify the cost?** Its W/L/no-result is {wln(W)}, versus Bounded {wln(B)}. Costs: {W['totals']['provider_requests']} versus {B['totals']['provider_requests']} requests, {W['totals']['total_tokens']:,} versus {B['totals']['total_tokens']:,} tokens, and {W['totals']['provider_latency_seconds']:.2f} versus {B['totals']['provider_latency_seconds']:.2f} provider seconds. Per turn, requests are {W['per_turn']['provider_requests']:.3f} versus {B['per_turn']['provider_requests']:.3f}. No value threshold was frozen to declare a small outcome gain worth that cost. Caps, early forfeits and uncertainty prevent a final cost-quality ranking.")
p('11. **Is Heuristic V2 stronger in the observed matchups?** Its matchup-specific W/L/no-result is '+ '; '.join(a+' '+wln(aa[a]['heuristic']) for a in arms)+'. This describes the observed dominance without pooling three different matchups into a homogeneous skill estimate. Its policy is unchanged; tactical weakness is benchmark data.')
stops=sum(aa[a]['end_turn']['count'] for a in arms)
p(f"12. **Are intentional stops mechanically and tactically reasonable?** All {stops} observed explicit EndTurns had zero subsequent provider requests within the turn. Counts/immediate stops: "+'; '.join(f"{a} {aa[a]['end_turn']['count']}/{aa[a]['end_turn']['immediate']}" for a in arms)+'. Stops with a legal single-action damaging opportunity: '+ '; '.join(f"{a} {aa[a]['end_turn']['damaging_opportunity_stops']}" for a in arms)+'. These are candidate premature-looking stops, not proof an attack was strategically preferable. Mechanical correctness is verified; overall tactical reasonableness remains limited to objective trace facts, with no model judge.')
p('13. **Has an actual contract defect appeared?** No observed hard integrity failure occurred in source/runtime checks, exact replay, request accounting, schedule/bindings, immutable evidence or no-fallback audits. Saved structured output and validators make repair failures interpretable. Exact replay is not a proof of ideal benchmark design, but there is no evidence supporting a mid-study contract change.')
p('14. **Is the study still interpretable as designed?** Yes, as a fixed imperfect Luna policy under three fixed control strategies against unchanged Heuristic V2 on one canonical opening. Recovery, output validity, outcomes and resource exposure remain separate. No tuning or early stopping based on apparent significance occurred. The intended sample remains 100/control, and confirmatory analysis remains reserved for the full cohort.')
p('## Objective long-game and Fireball evidence')
allrows=[json.loads(s) for s in (root/'results.jsonl').read_text().splitlines() if s]
pressure=[r for r in allrows if r['arm']=='bounded' and r['metrics'][r['luna_side']]['core_damage_dealt']>0]
if pressure:
    p('Every Bounded match with nonzero Core damage is listed below, so observed pressure is retained alongside its terminal outcome. This is a descriptive subset; the full outcome denominator remains all 80 matches.')
    table(['Match','Side','Core damage','Outcome/cause','Requests','Player turns'],[[r['match_id'],r['luna_side'],r['metrics'][r['luna_side']]['core_damage_dealt'],r['luna_outcome']+'/'+r['terminal_cause'],r['requests'],r['player_turns']] for r in pressure])
capfacts=focus['cumulative']['cap_gameplay']
if capfacts:
    table(['Cap','Luna turns','Requests','Repairs','EndTurns','Luna/Heuristic revives','Luna Core damage'],[[x['match_id'],x['luna_turns'],x['requests'],x['repairs'],x['end_turns'],f"{x['luna_revives']}/{x['heuristic_revives']}",x['luna_core_damage']] for x in capfacts])
p('These trace counts distinguish long-game decision exposure from repair volume. Repeated legal actions, unit downs, revivals and healing can be described directly; hidden reasoning, unwillingness to stop or a general causal stalemate mechanism cannot be inferred. Cap Core/unit configurations and final hashes are in cap-details.json.')
table(['Control','Fireballs','Enemy-only/mixed/friendly-only/empty','Enemy/friendly damage','Enemy/friendly downs'],[[a,aa[a]['totals']['fireball'],'/'.join(str(aa[a]['totals'][k]) for k in ('enemy_only_fireballs','mixed_fireballs','friendly_only_fireballs','empty_fireballs')),f"{aa[a]['fireball']['enemy_damage']}/{aa[a]['fireball']['friendly_damage']}",f"{aa[a]['fireball']['enemy_downs']}/{aa[a]['fireball']['friendly_downs']}"] for a in arms])
p('Immediate engine-winner consequences are listed in the cumulative report. Cast counts and friendly-fire patterns are descriptive; repeated revive cycles and unequal duration affect exposure. They do not establish internal Fireball comprehension.')
p('## Resources and projections')
fields=('provider_requests','input_tokens','cached_input_tokens','output_tokens','reasoning_tokens','total_tokens','provider_latency_seconds','backend_thinking_seconds')
table(['Resource','Batch 6','Batch 7','Batch 8','Cumulative 240'],[[k,*[f"{sum(d[f'batch_{b}']['arms'][a]['totals'][k] for a in arms):,.3f}" for b in (6,7,8)],f'{total(k):,.3f}'] for k in fields])
table(['Control','W/L/no-result','Win rate','Wilson 95%'],[[a,wln(aa[a]),pct(aa[a]['win_rate']),aa[a]['wilson_95']] for a in arms])
table(['Resource','Remaining 60 estimate','Full 300 estimate'],[['Requests',f"{total('provider_requests')*.25:,.2f}",f"{total('provider_requests')*1.25:,.2f}"],['Tokens',f"{total('total_tokens')*.25:,.0f}",f"{total('total_tokens')*1.25:,.0f}"],['Provider hours',f"{total('provider_latency_seconds')*.25/3600:.4f}",f"{total('provider_latency_seconds')*1.25/3600:.4f}"]])
p('Projections use observed per-control rates with 20 matches/control remaining. Caps and forfeits censor natural cost; these are estimates, not confidence bounds or authorization. Cached input is part of input; reasoning tokens part of output. Provider and backend times overlap. Process wall timings and sensitivity are in the cumulative report. No frozen pricing exists, so no dollars are estimated.')
p('## Decision and next authorization')
p('At 80/control, the large truncation reduction persists: Bounded has 86.1% fewer final truncations than Strict, versus 88.2% fewer at halfway. Positive recovery remains descriptively stable near 89%. The request premium is not stable across individual batches; its cumulative per-match value increased while its per-turn value decreased. No win advantage over Strict has emerged, although Bounded has more observed Core damage, downs and Finishes. These combat differences are descriptive and affected by unequal trajectories and repair forfeits.')
p('The higher Bounded repair-forfeit burden persists in the cumulative sample (36.25% versus 25.00% for Strict), a difference of 11.25 percentage points. It is not uniformly higher in every new batch: Batches 6 and 8 were tied, while Batch 7 had four versus two. The evidence therefore supports a descriptive imbalance, dominated by geometry failures and associated with full-turn planning, without identifying a stochastic or causal explanation. All 1,899 newly authorized requests returned normally; no recorded transport failure accounts for these forfeits.')
p('The Stepwise tail reflects long sequences of accepted actions, not mainly repair attempts: the capped games lasted 45–47 Luna turns, with only 0–6 repairs each. Fourteen Red-side caps include extensive repeated downs and heuristic revivals, without Luna Core damage. The Blue-side MATCH-058 cap had 39 explicit EndTurns and no revivals by either agent. Intentional stopping therefore occurred even in a capped game; a universal failure-to-stop explanation is unsupported. These are objective trace patterns consistent with recurrent low-progress play, not a claim about hidden reasoning or the uncapped counterfactual.')
p('**Continue unchanged. Recommend authorizing Batches 9–10 together**, with separate frozen integrity gates, independent 1,700-request ceilings and all existing per-control/per-match/global limits. Eight batches provide operational calibration; no integrity concern warrants splitting the last two authorizations. Tactical results must not change the study design. This recommendation is not executed: the runner stopped at Batch 8.')
p('[Batch 6 report](../arena-case-study-live-v1-06/batch-6-report.md) · [Batch 6 gate](../arena-case-study-live-v1-06/batch-6-gate.md) · [Batch 7 report](../arena-case-study-live-v1-07/batch-7-report.md) · [Batch 7 gate](../arena-case-study-live-v1-07/batch-7-gate.md) · [Batch 8 report](batch-8-report.md) · [Cumulative report](cumulative-batches-1-8-report.md) · [Repair forensics](repair-forensics.md) · [Paired mechanics and diagnostics](extra-analysis.md) · [Figures](figures.md)')
(root/'decision.md').write_text('\n'.join(lines),encoding='utf-8')
print(json.dumps(dict(success=True,questions_answered=14,recommendation='Batches 9–10; not executed')))
